# Generated by Django 4.1.7 on 2023-03-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_department_location_employees_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
